### ISSUE TITLE
Multiple servers

### ISSUE THREAD

**Issue by creativegaffers** [kylepaulsen/ValheimWebMap#12]
I installed the mod on an old server to make sure I could get it working before we start up a fresh sever in a few days, what is the best way to reset everything for the new server?  Should I just delete the map_data folder under the WebMap plugin directory?

**Comment by Florian-S-Dev** [comment]
Yes, you can just delete the map_data. If no map_data is found all relevant data will be generated. On my modding test server I do this all the time and it works great.

**Comment by creativegaffers** [comment]
Thanks much.  Mod seems great, looking forward to using it.
