### ISSUE TITLE
The site does not work correctly

### ISSUE THREAD

**Issue by 1fr4m3** [kylepaulsen/ValheimWebMap#7]
Greetings.

Installed your mod today. Everything works without errors, there is nothing in the console.
The site does not display a map, the left menu does not work, does not display pins. But at the same time, in the folder with the dedicated server, everything is created (files). Created an image with a map, pins, etc., but displays nothing on the site.

When enabled, display on the map for everyone
I appear, movements are visible
Perhaps these are all problems on my part. But I still ask for help

![image](https://user-images.githubusercontent.com/80629984/115398332-19199380-a1f8-11eb-955b-36e36f990b6c.png)
![image](https://user-images.githubusercontent.com/80629984/115398417-32224480-a1f8-11eb-8d98-f2c04e2f98fc.png)
![image](https://user-images.githubusercontent.com/80629984/115398536-4ebe7c80-a1f8-11eb-9b7c-afb73d974ac6.png)
![image](https://user-images.githubusercontent.com/80629984/115398707-7d3c5780-a1f8-11eb-84e5-ea7af14a2a8c.png)
![image](https://user-images.githubusercontent.com/80629984/115398982-c1c7f300-a1f8-11eb-8a87-3b46856cc492.png)
![image](https://user-images.githubusercontent.com/80629984/115399229-094e7f00-a1f9-11eb-8dcd-0f3fc4440f1d.png)
![image](https://user-images.githubusercontent.com/80629984/115399257-0eabc980-a1f9-11eb-96d9-8fdee079abfe.png)

**Comment by kylepaulsen** [comment]
This is odd. What browser are you using? And there were no browser console errors (F12 in most modern browsers). The only things I could think of is that maybe you need to zoom in a bit using mousewheel (the map starts out very zoomed out). But even then, you should be seeing pins. I wonder if you tried loading the page too soon after server start? Maybe try reloading the page after you are in game.

**Comment by rysson** [comment]
I suggest to install last version (1.1.0), released 20 min ago (there was changes in URLs for config and map), next check errors in a browser dev console, as @kylepaulsen wrote.
Next check network transfer files (the same browser dev console).

If movement works websocket is connected.

**Comment by 1fr4m3** [comment]
![image](https://user-images.githubusercontent.com/80629984/115543899-f5ffea00-a2b2-11eb-9e53-88da3fcf20c7.png)
![image](https://user-images.githubusercontent.com/80629984/115544008-1def4d80-a2b3-11eb-98ff-8538d38376c2.png)

**Comment by rysson** [comment]
Oh, JSON prepared by mod has some issue I guess.

Could you type here:
- your `config` (file from server map mod),
-  content of sent `config` (5th file on your network list) – you can get it browser dev console.

Those configs differs, first if editable source, second is prepared by map mod for JS front-end.

**Comment by 1fr4m3** [comment]
> Oh, JSON prepared by mod has some issue I guess.
> 
> Could you type here:
> 
> * your `config` (file from server map mod),

`{
    "// lines that look like this are comments and dont do anything.": 0,

    "// http server listens on below port. Default: 3000": 0,
    "server_port": 3000,

    "// A larger explore_radius reveals the map more quickly. Default: 100": 0,
    "explore_radius": 100,

    "// How zoomed in should the web map start at? Higher is more zoomed in. Default: 200": 0,
    "default_zoom": 200,

    "// How many pins each client is allowed to make before old ones start being deleted. Default: 50": 0,
    "max_pins_per_user": 50,

    "// How often do we send position data to web browsers in seconds. Default: 0.5": 0,
    "player_update_interval": 0.5,

    "// How often do we update the fog texture on the server in seconds. Default: 1": 0,
    "update_fog_texture_interval": 1,

    "// How often do we save the fog texture in seconds. Default: 30": 0,
    "save_fog_texture_interval": 30,

    "// Should the server cache web files to be more performant? Default: true": 0,
    "cache_server_files": true,

    "// How large is the map texture? Probably dont change this. Default: 2048": 0,
    "texture_size": 2048,

    "// How many in game units does a map pixel represent? Probably dont change this. Default: 12": 0,
    "pixel_size": 12
}`

> * content of sent `config` (5th file on your network list) – you can get it browser dev console.

`{"world_name":"TEST","world_start_pos": "-2,427281,37,2745,-1,760558","default_zoom":200,"texture_size":2048,"pixel_size":12,"update_interval":0,5,"explore_radius":100}`

> 
> Those configs differ, first if editable source, second is prepared by map mod for JS front-end.
> 
> EDIT: Do you upgrade mode to 1.1.0 version? And do you make full reload in the browser (ex. Shit-Ctrl-R)?
Yes. And showed new error after Shift-Ctrl-R.
![image](https://user-images.githubusercontent.com/80629984/115554276-59901480-a2bf-11eb-8a1a-3baa03a13ad7.png)

**Comment by rysson** [comment]
Thanks a lot! I see error `"update_interval":0,5` I suppose decimal point in your language is comma `,` (like in mine, but I have English set on server). Fanny issue.

I don't know C#, but if I will have to fix it I'll try to change:
```diff
diff --git a/WebMap/Config.cs b/WebMap/Config.cs
index 9abeaa8..9f5af00 100644
--- a/WebMap/Config.cs
+++ b/WebMap/Config.cs
@@ -135,7 +135,7 @@ namespace WebMap {
             sb.Append($"\"default_zoom\":{DEFAULT_ZOOM},");
             sb.Append($"\"texture_size\":{TEXTURE_SIZE},");
             sb.Append($"\"pixel_size\":{PIXEL_SIZE},");
-            sb.Append($"\"update_interval\":{PLAYER_UPDATE_INTERVAL},");
+            sb.Append($"\"update_interval\":{PLAYER_UPDATE_INTERVAL.toString("G", System.Globalization.CultureInfo.InvariantCulture)},");
             sb.Append($"\"explore_radius\":{EXPLORE_RADIUS}");
             sb.Append("}");
 ```

We have to wait for @kylepaulsen.

BTW. `favicon.ico` is only website icon, there is no one in web map mod. Maybe @kylepaulsen add one someday. Built-in or even custom.

**Comment by rysson** [comment]
@1fr4m3, like workaround you can change locale (language) on your server or set only integer instead floats (ex. `"update_interval": 1`).

**Comment by kylepaulsen** [comment]
Hey thanks @rysson and @1fr4m3 for the investigation. I'll try to get this fix out soon.

**Comment by 1fr4m3** [comment]
> @1fr4m3, like workaround you can change locale (language) on your server or set only integers instead floats (ex. `"update_interval": 1`).

ye, its worked
![image](https://user-images.githubusercontent.com/80629984/115707142-7ab83a00-a37f-11eb-9fea-fd753c8c44e6.png)

**Comment by 1fr4m3** [comment]
I also noticed that ping and pins
![Screenshot_7](https://user-images.githubusercontent.com/80629984/115707998-80fae600-a380-11eb-9bd9-8f3f981eedf4.jpg)
![Screenshot_6](https://user-images.githubusercontent.com/80629984/115708003-81937c80-a380-11eb-9adb-7d4e48aefc7e.jpg)

 is displayed not where I put it.

![Screenshot_4](https://user-images.githubusercontent.com/80629984/115707816-48f3a300-a380-11eb-92f7-e9b87ed7cc31.jpg)
![Screenshot_5](https://user-images.githubusercontent.com/80629984/115707819-498c3980-a380-11eb-9e99-a703f2b30fd0.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/80629984/115707821-4a24d000-a380-11eb-8230-faeb036ba1f5.jpg)

**Comment by 1fr4m3** [comment]
after refreshing the page, the pin was removed and a silhouette appeared

![image](https://user-images.githubusercontent.com/80629984/115708524-2d3ccc80-a381-11eb-9255-b011779c4ceb.png)

**Comment by kylepaulsen** [comment]
@1fr4m3 I just updated the mod to v1.1.1
I'm hoping this version resolves all these issues. Let me know if you are able to try it and it works.

**Comment by kylepaulsen** [comment]
Oh and you may need to delete `BepInEx/plugins/WebMap/map_data/your_map_name/pins.csv`

**Comment by 1fr4m3** [comment]
> @1fr4m3 I just updated the mod to v1.1.1
> I'm hoping this version resolves all these issues. Let me know if you are able to try it and it works.

It works, thanks!

Another question, is it possible to open the entire map at once without fog? Without changing `"explore_radius": 100`?

**Comment by 1fr4m3** [comment]
**Everything works, thank you very much!**

**Comment by kylepaulsen** [comment]
👍
