### ISSUE TITLE
[Suggestion] Allow for web/non-ingame pin updates

### ISSUE THREAD

**Issue by runnane** [kylepaulsen/ValheimWebMap#9]
Hi, great work on this mod 👍 
I am not a unity developer and have not made any attempts to explore the BepInEx code.
However - I was wondering if you have made any thoughts on how to implement a web/non-ingame way of updating the pins? As of now we are updating the csv, and then need to force the mod to run Awake() - and as far as I can see, this is only done on initialization. So we restart the server. This, of course, is messy.
Do you see an option for using a persistant external storage in-game aswell, and not just mem? So we can do updates externally that will not be wiped if we do ingame updates?
I started working on a change so we can use the WS routing to modify the pins from web, but I wanted to check if something else is "in the works" first :)

Thanks,
Jon

**Comment by kylepaulsen** [comment]
I did think about this early on but decided against it to avoid abuse from people who are not apart of the server. If there was a login or something, maybe that would be a good way to do it. Currently nothing is in the works.

**Comment by runnane** [comment]
Ok, thanks!
I will fork and look into this.
